### ISSUE TITLE
Get unbuffered text I/O error on Python 3.6 

### ISSUE THREAD

**Issue by parvezmkhan** [arnaudsj/python-daemon#11]
Thanks a lot for your work.
I am facing below error.

daemon/runner.py", line 135, in _open_streams_from_app_stream_paths
    app.stderr_path, 'w+t', buffering=0)
ValueError: can't have unbuffered text I/O

Removing buffering fixes in my test

**Comment by parvezmkhan** [comment]
This is fixed in fork closing it.

**Comment by mr-chen-king** [comment]
Thanks a lot for your work

when i use it in python 3.7 this problem appear again
File "/usr/local/python37/lib/python3.7/site-packages/daemon/runner.py", line 114, in __init__
    self._open_streams_from_app_stream_paths(app)
  File "/usr/local/python37/lib/python3.7/site-packages/daemon/runner.py", line 135, in _open_streams_from_app_stream_paths
    app.stderr_path, 'w+t', buffering=0)
ValueError: can't have unbuffered text I/O
